export const GET_HERO_IMAGE_START = "GET_HERO_IMAGE_START";
export const GET_HERO_IMAGE_SUCCESS = "GET_HERO_IMAGE_SUCCESS";
export const GET_HERO_IMAGE_FAILED = "GET_HERO_IMAGE_FAILED";

export const GET_MOVIES_START = "GET_MOVIES_START";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";

export const GET_MOVIE_BY_ID_START = "GET_MOVIE_BY_ID_START";
export const GET_MOVIE_BY_ID_SUCCESS = "GET_MOVIE_BY_ID_SUCCESS";
export const GET_MOVIE_BY_ID_FAILED = "GET_MOVIE_BY_ID_FAILED";

export const GET_PRODUCTION_COMPANY_BY_ID_START = "GET_PRODUCTION_COMPANY_BY_ID_START";
export const GET_PRODUCTION_COMPANY_BY_ID_SUCCESS = "GET_PRODUCTION_COMPANY_BY_ID_SUCCESS";
export const GET_PRODUCTION_COMPANY_BY_ID_FAILED = "GET_PRODUCTION_COMPANY_BY_ID_FAILED";